# Generated by Django 3.1.2 on 2020-10-27 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_ejemplo2'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplo2',
            name='ejemplo_campo2',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
